name: publish

on:
  push:
    tags:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: package
      run: |
        python setup.py sdist
    - name: publish
      if: ${{ github.ref == 'ref/head/master' }}
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_TOKEN }}
