name: Build

on: [push, pull_request]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install --dev
    - name: Lint with flake8
      run: |
        pipenv run flake8 --max-line-length 120
    - name: SAST
      run: |
        pipenv run safety check
        pipenv run bandit -r -x ./tests .
    - name: pytest
      run: |
        cd tests && pipenv run pipenv run pytest --cov=.. --cov-report=xml
    - uses: codecov/codecov-action@v1
      with:
        file: tests/coverage.xml
        token: ${{ secrets.CODECOV_TOKEN }}
    - name: package
      run: |
        python setup.py sdist
    - name: publish
      if: startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_TOKEN }}
